### PR TITLE
Integrate with Klaro and GA

### PR DESCRIPTION
**Pull request by kaichaosun**
Related to https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/227

cc @jimmychu0807

### CODE REVIEW

**Comment by kaichaosun** [comment]
Seems the style is broken

**Comment by jimmychu0807** [comment]
look good to me.

**Comment by jimmychu0807** [comment]
@kaichaosun 

- I run the website in localhost. I don't see the klaro consent panel that I can configure. It is only viewable after deployed?

- I cannot verify the GA is successfully connected and start populating data there. But there is no JS error, a good sign. You have a chance to view if GA data start populating with the new config? Or it is also something verifiable only after deployed under `https://substrate.dev`?

**Comment by kaichaosun** [comment]
* It should show up if you include the changes, can you test by removing the Local Storage from Application in the developer tool?
image
* The local data is not collected in analytics for local, not sure why. I will check if it works after go live.

@jimmychu0807

**Comment by shawntabrizi** [comment]
Thank you @kaichaosun!

Works great as far as I can tell :)

**Pull request merged**
