### PR TITLE
Fix comment

### PR DESCRIPTION
**Pull request by seabornlee**

### CODE REVIEW

**Comment by shawntabrizi** [comment]
@riusricardo I think this is fine. He is just making the changes in the browser interface, so you can't really consolidate it.

**Comment by riusricardo** [comment]
@shawntabrizi I just wanted to make a point to prevent getting many PRs from the same date and person for different typos. It's great to catch this typos and very much appreciated. As a future recommendation it will be better to get one PR and get a cleaner commit history.

**Comment by shawntabrizi** [comment]
Right, but at the cost of people possibly not submitting the fixes?

The Github UI only allows for things like this. I think we should be thanking them for any and all contributions rather than asking for more :)

But I agree, in general.

**Comment by seabornlee** [comment]
> Right, but at the cost of people possibly not submitting the fixes?
> 
> The Github UI only allows for things like this. I think we should be thanking them for any and all contributions rather than asking for more :)
> 
> But I agree, in general.

Thanks for your understanding. I am new to open source world, your attitude encouraged me to contribute more. And I also will take the advice of @riusricardo to be a better contributor like both of you.

**Pull request merged**
