### PR TITLE
fix Rust code in 'refactoring-our-code'

### PR DESCRIPTION
**Pull request by apopiak**
The Rust code on this page had some errors so I fixed it. (Relies on specifying some imports correctly, but so did the original.)
Verified to (at least) compile in my personal branch of the workshop.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
So this means the workshop is no longer compatible with v1.0 right?

Should the [instructions](https://github.com/substrate-developer-hub/substrate-collectables-workshop/blob/master/0/running-a-custom-node.md#running-a-custom-node) be updated accordingly?

Is it a better idea to do all the updating on a separate branch?

**Comment by apopiak** [comment]
@JoshOrndorff I compiled it with v1.0.

**Comment by JoshOrndorff** [comment]
Oh great. I didn't realize `DispatchResult` would work there. Glad to hear it still works.

**Comment by apopiak** [comment]
It does rely on a renaming import (`use support::dispatch::Result as DispatchResult`) which I'm happy to make explicit in the snippet. This is necessary because the `adder` function needs a different Result type.

**Comment by shawntabrizi** [comment]
@apopiak it might be better just to explicitly return `Result<(), &'static str>` which relies on no renaming or imports.

**Pull request merged**
